/**
 * PlotPanel.jsx
 * 
 * Component for rendering Plotly charts from solver results.
 * Supports line plots, scatter plots, and multiple Y variables.
 * 
 * NOTE FOR DEVELOPERS/AGENTS:
 * This component uses react-plotly.js to render interactive charts.
 * The plot configurations are generated by the backend solver/plotting.py module.
 * 
 * Uses dynamic import to gracefully handle missing plotly dependency.
 */

import React, { useState, useEffect } from 'react';
import './PlotPanel.css';

/**
 * PlotPanel - Renders Plotly charts from backend-generated configurations
 * Uses dynamic import to avoid crashing if react-plotly.js isn't installed.
 * 
 * @param {Array} plotConfigs - Array of Plotly configuration objects from backend
 */
export const PlotPanel = ({ plotConfigs }) => {
    const [Plot, setPlot] = useState(null);
    const [loadError, setLoadError] = useState(null);
    const [expandedPlot, setExpandedPlot] = useState(null);

    // Dynamically load plotly
    useEffect(() => {
        import('react-plotly.js')
            .then(module => {
                setPlot(() => module.default);
            })
            .catch(err => {
                console.error('Failed to load react-plotly.js:', err);
                setLoadError('Plotly not installed. Run: npm install');
            });
    }, []);

    if (!plotConfigs || plotConfigs.length === 0) {
        return null;
    }

    if (loadError) {
        return (
            <div className="plot-panel-error">
                <p>📊 Plotting requires additional dependencies.</p>
                <p>Run: <code>cd frontend && npm install</code></p>
            </div>
        );
    }

    if (!Plot) {
        return (
            <div className="plot-panel-loading">
                <p>Loading plot library...</p>
            </div>
        );
    }

    const handlePlotClick = (idx) => {
        setExpandedPlot(expandedPlot === idx ? null : idx);
    };

    return (
        <div className="plot-panel">
            <div className="plot-panel-header">
                <h4>📊 Plots</h4>
                <span className="plot-count">{plotConfigs.length} plot{plotConfigs.length > 1 ? 's' : ''}</span>
            </div>
            <div className="plots-container">
                {plotConfigs.map((config, idx) => (
                    <div
                        key={idx}
                        className={`plot-wrapper ${expandedPlot === idx ? 'expanded' : ''}`}
                        onClick={() => handlePlotClick(idx)}
                    >
                        <Plot
                            data={config.data}
                            layout={{
                                ...config.layout,
                                autosize: true,
                            }}
                            config={{
                                responsive: true,
                                displayModeBar: true,
                                modeBarButtonsToRemove: ['lasso2d', 'select2d'],
                                displaylogo: false
                            }}
                            style={{ width: '100%', height: expandedPlot === idx ? '600px' : '450px' }}
                            useResizeHandler={true}
                        />
                    </div>
                ))}
            </div>
        </div>
    );
};

/**
 * ArrayResultSummary - Shows a summary of array result values
 * 
 * @param {string} variable - Variable name
 * @param {Array} values - Array of values
 * @param {string} unit - Unit string
 */
export const ArrayResultSummary = ({ variable, values, unit, onClick }) => {
    if (!Array.isArray(values) || values.length === 0) {
        return null;
    }

    const min = Math.min(...values.filter(v => !isNaN(v)));
    const max = Math.max(...values.filter(v => !isNaN(v)));
    const count = values.length;

    const formatValue = (val) => {
        if (typeof val !== 'number' || isNaN(val)) return 'N/A';
        return val.toPrecision(4).replace(/\.?0+$/, '');
    };

    return (
        <div className="array-result-summary" onClick={onClick}>
            <div className="array-header">
                <span className="var-name">{variable}</span>
                <span className="array-badge">[{count} values]</span>
            </div>
            <div className="array-stats">
                <span className="stat">
                    <span className="stat-label">min:</span>
                    <span className="stat-value">{formatValue(min)}</span>
                </span>
                <span className="stat">
                    <span className="stat-label">max:</span>
                    <span className="stat-value">{formatValue(max)}</span>
                </span>
                {unit && (
                    <span className="array-unit">[{unit}]</span>
                )}
            </div>
        </div>
    );
};

/**
 * PlotConfigPanel - UI for configuring plots from array results (optional enhancement)
 * Allows users to manually select X/Y variables for plotting
 */
export const PlotConfigPanel = ({
    arrayVariables,
    onCreatePlot,
    isOpen,
    onClose
}) => {
    const [xVar, setXVar] = useState('');
    const [yVars, setYVars] = useState([]);
    const [plotType, setPlotType] = useState('line');

    if (!isOpen || !arrayVariables || arrayVariables.length === 0) {
        return null;
    }

    const handleYVarToggle = (varName) => {
        setYVars(prev =>
            prev.includes(varName)
                ? prev.filter(v => v !== varName)
                : [...prev, varName]
        );
    };

    const handleCreate = () => {
        if (xVar && yVars.length > 0) {
            onCreatePlot({
                x_var: xVar,
                y_vars: yVars,
                plot_type: plotType
            });
            onClose();
        }
    };

    return (
        <div className="plot-config-overlay" onClick={onClose}>
            <div className="plot-config-panel" onClick={e => e.stopPropagation()}>
                <div className="config-header">
                    <h4>Create Plot</h4>
                    <button className="close-btn" onClick={onClose}>×</button>
                </div>

                <div className="config-body">
                    <div className="config-section">
                        <label>X-Axis Variable:</label>
                        <select value={xVar} onChange={e => setXVar(e.target.value)}>
                            <option value="">Select...</option>
                            {arrayVariables.map(v => (
                                <option key={v} value={v}>{v}</option>
                            ))}
                        </select>
                    </div>

                    <div className="config-section">
                        <label>Y-Axis Variables:</label>
                        <div className="y-var-list">
                            {arrayVariables.filter(v => v !== xVar).map(v => (
                                <label key={v} className="y-var-checkbox">
                                    <input
                                        type="checkbox"
                                        checked={yVars.includes(v)}
                                        onChange={() => handleYVarToggle(v)}
                                    />
                                    {v}
                                </label>
                            ))}
                        </div>
                    </div>

                    <div className="config-section">
                        <label>Plot Type:</label>
                        <select value={plotType} onChange={e => setPlotType(e.target.value)}>
                            <option value="line">Line</option>
                            <option value="scatter">Scatter</option>
                        </select>
                    </div>
                </div>

                <div className="config-footer">
                    <button className="cancel-btn" onClick={onClose}>Cancel</button>
                    <button
                        className="create-btn"
                        onClick={handleCreate}
                        disabled={!xVar || yVars.length === 0}
                    >
                        Create Plot
                    </button>
                </div>
            </div>
        </div>
    );
};

export default PlotPanel;
